export { default as Beranda }         from "./Beranda"
export { default as Login }         from "./login"
export { default as SignUp }         from "./SignUp"
export { default as Formlogin }         from "./Formlogin"
export { default as Maps }         from "./maps"
export { default as Camera }         from "./camera"